routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('books.index');
});

Route::post('books/{book}/borrow', 'BookController@borrow')->name('books.borrow');
Route::post('books/{book}/retrieve', 'BookController@retrieve')->name('books.retrieve');
Route::post('books/data', 'BookController@data')->name('books.data');
Route::resource('books', 'BookController');

Route::post('categories/data', 'CategoryController@data')->name('categories.data');
Route::resource('categories', 'CategoryController');

Route::post('users/data', 'UserController@data')->name('users.data');
Route::resource('users', 'UserController');

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Model
{
    use SoftDeletes;

    protected $fillable = ['name', 'email'];

    protected $dates =['created_at', 'updated_at', 'deleted_at'];

    function books(){
        return $this->hasMany('App\Book');
    }

    function getBookCountAttribute(){
    	return $this->books()->count();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    private $validatorRules = [
        'name' => 'required|min:3|max:255',
        'email' => 'required|email|unique:users,email'
    ];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, $this->validatorRules);
        $user = User::create([
            'name' => $request->name,
            'email' => $request->email
            ]);
        if($user){
            return redirect()->route('users.show', ['user'=>$user->id]);
        }else{
            return redirect()->route('users.create', ['errors' => ['unespecified_error' => 'there was a problem storing the user']]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id)->load('books');
        if($user)
            return view('users.show', ['user' => $user]);
        else
            return redirect()->route('users.index', ['error' => 'The specified user could not be found']);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        if($user)
            return view('users.edit', ['user' => $user]);
        else
            return redirect()->route('users.index',['error' => 'The specified user could not be found']);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $new_rules = $this->validatorRules;
        $new_rules['email'] = 'required|email|unique:users,email,'.$user->id;
        $this->validate($request, $new_rules);
        if($user){
            $user->name = $request->name;
            $user->email = $request->email;
            $user->save();
            return redirect()->route('users.show', ['user'=>$user->id]);
        }
        else
            return redirect()->route('users.index')->with(['error' => 'The specified user could not be found']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if($user){
            if($user->delete())
                $json=['success' => true, 'msg' => 'the user was deleted'];
            else
                $json=['success' => flase, 'msg' => 'the user cold not be deleted'];
            return response()->json($json)->header('Content-Type', 'application/json');
        }
        else
            return response()->json(['success' => false, 'msg' => 'the specified user could not be found'])->header('Content-Type', 'application/json');
    }

    public function data(Request $request){
        $id = $request->has('id') ? $request->id : null;
        $name = $request->has('name') ? $request->name : null;
        $email = $request->has('email') ? $request->email : null;
        $book_id = $request->has('book_id') ? $request->book_id : null;

        $users_query = User::query();
        if($id)
            $users_query->whereId($id);
        if($name)
            $users_query->whereName($name);
        if($email)
            $users_query->whereDescription($email);

        $limit = 10;
        $totalTabs = ceil($users_query->count()/$limit);

        $index = $request->has('index') ? ($request->index > $totalTabs ? $totalTabs : $request->index) : 1;
        $offset = ($index-1)*$limit;

        $users = $users_query->take($limit)->skip($offset)->get();

        $formatted = '';
        foreach ($users as $user) {
            $formatted .= '<tr>';
            $formatted .= ' <td>'.$user->id.'</td>';
            $formatted .= ' <td>'.$user->name.'</td>';
            $formatted .= ' <td>'.$user->email.'</td>';
            $formatted .= ' <td>'.$user->book_count.'</td>';
            $formatted .= ' <td>';
            if($book_id){
                $formatted .= '     <a href="'.route('books.borrow',$book_id).'" class="lend_book" data-id="'.$user->id.'"><span class="glyphicon glyphicon-ok" aria-hidden="true" title="Lend Book"></span></a>';
            }else{
                $formatted .= '     <a href="'.route('users.show',$user->id).'"><span class="glyphicon glyphicon-info-sign" aria-hidden="true" title="Info"></span></a>';
                $formatted .= '     <a href="'.route('users.edit',$user->id).'"><span class="glyphicon glyphicon-edit" aria-hidden="true" title="Edit"></span></a>';
                $formatted .= '     <a href="'.route('users.destroy',$user->id).'" class="destroy_button"><span class="glyphicon glyphicon-remove red" aria-hidden="true" title="Remove"></span></a>';
            }
            $formatted .= ' </td>';
            $formatted .= '</tr>';
        }

        $controls = PaginationHelper::getPaginationControls($index, $totalTabs);

        return response()->json(['success' => true, 'data' => $formatted, 'controls' => $controls])->header('Content-Type', 'application/json');
    }
}

resources/views/users/create.blade.php
@extends('layouts.default')

@section('title', 'User Creation')

@section('content')
	<h1>
        User Create
    </h1>
    
    @if (count($errors) > 0)
	    <div class="alert alert-danger">
	    	<ul>
			    @foreach($errors->all() as $error)
			    	<li>{{ $error }}</li>
			    @endforeach
	    	</ul>
	    </div>
    @endif

	<div class="col-md-12 text-center">
		<form id="new_user" action="{{ route('users.store') }}" method="post">
			{{ csrf_field() }}
			<div class="form-group">
				<label for="name">Name:</label>
				<input type="text" name="name" id="name" placeholder="Name" pattern=".{3,}" required title="3 characters minimum">
			</div>
			<div class="form-group">
				<label for="email">e-mail:</label>
				<input type="email" name="email" id="email" placeholder="e-mail" pattern=".{3,}" required title="3 characters minimum">
			</div>
			<div class="form-group">
				<input type="submit" name="create_user" id="create_user" class="btn btn-primary">
			</div>
		</form>
	</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.default')

@section('title', 'User Edit')

@section('content')
	<h1>
        User Edit
    </h1>
    
    @if (count($errors) > 0)
	    <div class="alert alert-danger">
	    	<ul>
			    @foreach($errors->all() as $error)
			    	<li>{{ $error }}</li>
			    @endforeach
	    	</ul>
	    </div>
    @endif

	<div class="col-md-12 text-center">
		<form id="new_user" action="{{ route('users.update', $user->id) }}" method="post">
			{{ csrf_field() }}
			<input type="hidden" name="_method" value="PATCH">
			<div class="form-group">
				<label for="name">Name:</label>
				<input type="text" name="name" id="name" placeholder="Name" pattern=".{3,}" required title="3 characters minimum" value="{{ $user->name }}">
			</div>
			<div class="form-group">
				<label for="email">e-mail:</label>
				<input type="email" name="email" id="email" placeholder="e-mail" pattern=".{3,}" required title="3 characters minimum" value="{{ $user->email }}">
			</div>
			<div class="form-group">
				<input type="submit" name="update_user" id="update_user" class="btn btn-primary">
			</div>
		</form>
	</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.general_index')

@section('title', 'Categories')
@section('create_route', route('users.create'))

@section('table_head')
	<td><input type="number" name="id" id="id" placeholder="ID"></td>
	<td><input type="text" name="name" id="name" placeholder="Name"></td>
	<td><input type="email" name="email" id="email" placeholder="e-mail"></td>
	<td><input type="text" name="book_count" id="book_count" placeholder="Borrowed Books" disabled></td>
	<td><input type="text" name="actions" placeholder="Actions" disabled></td>
@endsection

@section('data_url', route('users.data'))

@section('filter_data')
	id: $('#id').val(),
	name: $('#name').val(),
	email: $('#email').val(),
@endsection

resources/views/users/show.blade.php
@extends('layouts.pagination_script')

@section('title', 'User View')

@section('header_content')
	<h1>
        User View <a href="{{ route('users.edit', $user->id) }}" class="pull_right"><span class="glyphicon glyphicon-edit" aria-hidden="true" title="Edit User"></a>
    </h1>
	<div class="col-md-12">
		<table>
			<tr>
				<td>ID</td><td>{{ $user->id }}</td>
			</tr>
			<tr>
				<td>Name</td><td>{{ $user->name }}</td>
			</tr>
			<tr>
				<td>e-mail</td><td>{{ $user->email }}</td>
			</tr>
		</table>
	</div>
	<h2>Books borrowed by this User</h2>
@endsection

@section('table_head')
	<td><input type="number" name="id" id="id" placeholder="ID"></td>
	<td><input type="text" name="name" id="name" placeholder="Name"></td>
	<td><input type="text" name="author" id="author" placeholder="Author"></td>
	<td><input type="text" name="category" id="category" placeholder="Category"></td>
	<td><input type="text" name="published_date" id="published_date" placeholder="Published Date"></td>
	<td><input type="text" name="actions" placeholder="Actions" disabled></td>
@endsection

@section('other_content')
	<div class="modal fade" id="returnBookModal" tabindex="-1" role="dialog" aria-labelledby="returnBookLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="returnBookLabel">Return Book</h4>
				</div>
				<div class="modal-body">
					<p>Are you shure you want to return this book?</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="button" href="#" class="btn btn-primary">OK</button>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('data_url', route('books.data'))

@section('filter_data')
	user_id: {{$user->id}},
	id: $('#id').val(),
	name: $('#name').val(),
	author: $('#author').val(),
	published_date: $('#published_date').val(),
@endsection

@section('custom_scripts')
	$('#returnBookModal').on('show.bs.modal', function (event) {
		var button = $(event.relatedTarget);
		var url = button.data('url');
		var modal = $(this);
		modal.find('.btn-primary').attr('href', url);
	})

	$('body').on('click', '.modal-footer > button.btn-primary', function(e) {
        e.preventDefault();
        var route = $(this).attr('href');
        $.ajax({
            type: "POST",
            url : route,
            data: {
                _token: "{{ csrf_token() }}"
            },
        }).done(function (result) {
            getData($('a.active').data('val'));
        }).fail(function () {
            alert('The data could not be loaded.');
        });
        $('#returnBookModal').modal('hide');
    });
@endsection