routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('books.index');
});

Route::post('books/{book}/borrow', 'BookController@borrow')->name('books.borrow');
Route::post('books/{book}/retrieve', 'BookController@retrieve')->name('books.retrieve');
Route::post('books/data', 'BookController@data')->name('books.data');
Route::resource('books', 'BookController');

Route::post('categories/data', 'CategoryController@data')->name('categories.data');
Route::resource('categories', 'CategoryController');

Route::post('users/data', 'UserController@data')->name('users.data');
Route::resource('users', 'UserController');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
	use SoftDeletes;

    protected $fillable = ['name', 'author', 'category_id', 'published_date'];

    protected $dates =['created_at', 'updated_at', 'deleted_at'];

    protected $casts = [
        'borrowed' => 'boolean',
    ];

    function getBorrowedAttribute(){
    	return $this->user;
    }

    function category() {
    	return $this->belongsTo('App\Category');
    }

    function user(){
    	return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Book;
use App\Category;

class BookController extends Controller
{
    private $validatorRules = [
        'name' => 'required|min:3|max:255',
        'author' => 'required|min:3|max:255',
        'category_id' => 'required|exists:categories,id',
        'published_date' => 'required|date'
    ];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::select('name')->get();
        return view('books.index', ['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::select('id','name')->get();
        return view('books.create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, $this->validatorRules);
        $book = Book::create([
            'name' => $request->name,
            'author' => $request->author,
            'category_id' => $request->category_id,
            'published_date' => $request->published_date
            ]);
        if($book){
            return redirect()->route('books.show', ['book'=>$book->id]);
        }else{
            return redirect()->route('books.create', ['errors' => ['unespecified_error' => 'there was a problem storing the book']]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $book = Book::find($id)->load('user', 'category');
        if($book)
            return view('books.show', ['book' => $book]);
        else
            return redirect()->route('books.index', ['error' => 'The specified book could not be found']);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::select('id','name')->get();
        $book = Book::find($id);
        if($book)
            return view('books.edit', ['book' => $book, 'categories' => $categories]);
        else
            return redirect()->route('books.index', ['error' => 'The specified book could not be found']);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, $this->validatorRules);
        $book = Book::find($id);
        if($book){
            $book->name = $request->name;
            $book->author = $request->author;
            $book->category_id = $request->category_id;
            $book->published_date = $request->published_date;
            $book->save();
            return redirect()->route('books.show', ['book'=>$book->id]);
        }
        else
            return redirect()->route('books.index', ['error' => 'The specified book could not be found']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::find($id);
        if($book){
            if($book->delete())
                $json=['success' => true, 'msg' => 'the book was deleted'];
            else
                $json=['success' => flase, 'msg' => 'the book cold not be deleted'];
            return response()->json($json)->header('Content-Type', 'application/json');
        }
        else
            return response()->json(['success' => false, 'msg' => 'the specified book could not be found'])->header('Content-Type', 'application/json');
    }

    public function data(Request $request){
        $id = $request->has('id') ? $request->id : null;
        $name = $request->has('name') ? $request->name : null;
        $author = $request->has('author') ? $request->author : null;
        $category_name = $request->has('category') ? $request->category : null;
        $published_date = $request->has('published_date') ? $request->published_date : null;
        $user_id = $request->has('user_id') ? $request->user_id : null;
        $category_id_param = $request->has('category_id') ? $request->category_id : null;

        if(!$category_id_param){
            if($category_name)
                $category_id = Category::whereName($category_name)->pluck('id')->first();
            else
                $category_id = null;
        }else{
            $category_id = $category_id_param;
        }

        $books_query = Book::with('category');
        if($id)
            $books_query->whereId($id);
        if($name)
            $books_query->whereName($name);
        if($author)
            $books_query->whereAuthor($author);
        if($category_id)
            $books_query->whereCategoryId($category_id);
        if($published_date)
            $books_query->wherePublishedDate($published_date);
        if($user_id)
            $books_query->whereUserId($user_id);

        $limit = 10;
        $totalTabs = ceil($books_query->count()/$limit);

        $index = $request->has('index') ? ($request->index > $totalTabs ? $totalTabs : $request->index) : 1;
        $offset = ($index-1)*$limit;

        $books = $books_query->take($limit)->skip($offset)->get();

        $formatted = '';
        foreach ($books as $book) {
            $formatted .= '<tr>';
            $formatted .= ' <td>'.$book->id.'</td>';
            $formatted .= ' <td>'.$book->name.'</td>';
            $formatted .= ' <td>'.$book->author.'</td>';
            if (!$category_id_param)
                $formatted .= ' <td>'.$book->category->name.'</td>';
            $formatted .= ' <td>'.$book->published_date.'</td>';
            if(!$user_id)
                $formatted .= ' <td>'.($book->borrowed ? '<span class="glyphicon glyphicon-ok" aria-hidden="true" title="Borrowed"></span>' : '').'</td>';
            $formatted .= ' <td>';
            $formatted .= '     <a href="'.route('books.show',$book->id).'"><span class="glyphicon glyphicon-info-sign" aria-hidden="true" title="Info"></span></a>';
            if(!$user_id && !$category_id_param){
                $formatted .= '     <a href="'.route('books.edit',$book->id).'"><span class="glyphicon glyphicon-edit" aria-hidden="true" title="Edit"></span></a>';
                $formatted .= '     <a href="'.route('books.destroy',$book->id).'" class="destroy_button"><span class="glyphicon glyphicon-remove red" aria-hidden="true" title="Remove"></span></a>';
            }
            if($user_id)
                $formatted .= '     <a href="#" class="return_book" data-toggle="modal" data-target="#returnBookModal" data-url="'.route('books.retrieve',$book->id).'"><span class="glyphicon glyphicon-ok" aria-hidden="true" title="Return Book"></span></a>';
            $formatted .= ' </td>';
            $formatted .= '</tr>';
        }

        $controls = PaginationHelper::getPaginationControls($index, $totalTabs);

        return response()->json(['success' => true, 'data' => $formatted, 'controls' => $controls])->header('Content-Type', 'application/json');
    }

    public function borrow(Request $request, $id){
        $this->validate($request, ['user_id' => 'required|exists:users,id']);

        $book = Book::find($id);
        if($book){
            $book->user_id = $request->user_id;
            $book->save();
            return response()->json(['success' => false, 'msg' => 'the book was successfully retrieved'])->header('Content-Type', 'application/json');
        }else
            return response()->json(['success' => false, 'msg' => 'the specified book could not be found'])->header('Content-Type', 'application/json');
    }

    public function retrieve($id){
        $book = Book::find($id);
        if($book){
            $book->user_id = null;
            $book->save();
            return response()->json(['success' => false, 'msg' => 'the book was successfully retrieved'])->header('Content-Type', 'application/json');
        }else
            return response()->json(['success' => false, 'msg' => 'the specified book could not be found'])->header('Content-Type', 'application/json');
    }

    public function returnModal(Request $request){
        $rules = ['route' => 'required'];
        
        $this->validate($request, $rules);

        $view = view('books.modals.return', ['route' => $request->route]);

        return response()->json(['success' => true, 'payload' => view('books.modals.return', ['route' => $request->route])->render()]);
    }

    public function lendModal(Request $request){
        $rules = [
            'route' => 'required',
            'user_id' => 'required|exists:users,id',
        ];
        $this->validate($request, $rules);

        $view = view('layouts.modals.lend', ['route' => $request->route, 'user_id' => $request->user_id]);

        return response()->json(['success' => true, 'payload' => view('layouts.modals.lend', ['route' => $request->route, 'user_id' => $request->user_id])->render()]);
    }
}

resources/views/books/create.blade.php
@extends('layouts.default')

@section('title', 'Book Creation')

@section('content')
	<h1>
        Book Create
    </h1>
    
    @if (count($errors) > 0)
	    <div class="alert alert-danger">
	    	<ul>
			    @foreach($errors->all() as $error)
			    	<li>{{ $error }}</li>
			    @endforeach
	    	</ul>
	    </div>
    @endif

	<div class="col-md-12 text-center">
		<form id="new_book" action="{{ route('books.store') }}" method="post">
			{{ csrf_field() }}
			<div class="form-group">
				<label for="name">Name:</label>
				<input type="text" name="name" id="name" placeholder="Name" pattern=".{3,}" required title="3 characters minimum">
			</div>
			<div class="form-group">
				<label for="author">Author:</label>
				<input type="text" name="author" id="author" placeholder="Author" pattern=".{3,}" required title="3 characters minimum">
			</div>
			<div class="form-group">
				<label for="category_id">Category:</label>
				<select name="category_id" id="category_id" required>
					@foreach($categories as $category)
						<option value="{{ $category->id }}">{{ $category->name }}</option>
					@endforeach
				</select>
			</div>
			<div class="form-group">
				<label for="published_date">Published Date:</label>
				<input type="date" name="published_date" id="published_date" max="{{ date('Y-m-d') }}">
			</div>
			<div class="form-group">
				<input type="submit" name="create_book" id="create_book" class="btn btn-primary">
			</div>
		</form>
	</div>
@endsection

resources/views/books/edit.blade.php
@extends('layouts.default')

@section('title', 'Book Edit')

@section('content')
	<h1>
        Book Edit
    </h1>
    
    @if (count($errors) > 0)
	    <div class="alert alert-danger">
	    	<ul>
			    @foreach($errors->all() as $error)
			    	<li>{{ $error }}</li>
			    @endforeach
	    	</ul>
	    </div>
    @endif

	<div class="col-md-12 text-center">
		<form id="new_book" action="{{ route('books.update', $book->id) }}" method="post">
			{{ csrf_field() }}
			<input type="hidden" name="_method" value="PATCH">
			<div class="form-group">
				<label for="name">Name:</label>
				<input type="text" name="name" id="name" placeholder="Name" pattern=".{3,}" required title="3 characters minimum" value="{{ $book->name }}">
			</div>
			<div class="form-group">
				<label for="author">Author:</label>
				<input type="text" name="author" id="author" placeholder="Author" pattern=".{3,}" required title="3 characters minimum" value="{{ $book->author }}">
			</div>
			<div class="form-group">
				<label for="category_id">Category:</label>
				<select name="category_id" id="category_id" required>
					@foreach($categories as $category)
						<option value="{{ $category->id }}" {!! $category->id == $book->category_id ? "select" : "" !!}>{{ $category->name }}</option>
					@endforeach
				</select>
			</div>
			<div class="form-group">
				<label for="published_date">Published Date:</label>
				<input type="date" name="published_date" id="published_date" max="{{ date('Y-m-d') }}" value="{{ $book->published_date }}">
			</div>
			<div class="form-group">
				<input type="submit" name="update_book" id="update_book" class="btn btn-primary">
			</div>
		</form>
	</div>
@endsection

resources/views/books/index.blade.php
@extends('layouts.general_index')

@section('title', 'Books')
@section('create_route', route('books.create'))

@section('table_head')
	<td><input type="number" name="id" id="id" placeholder="ID"></td>
	<td><input type="text" name="name" id="name" placeholder="Name"></td>
	<td><input type="text" name="author" id="author" placeholder="Author"></td>
	<td><input type="text" name="category" id="category" placeholder="Category" list="categories">
		<datalist id="categories">
			@foreach($categories as $category)
				<option value="{{ $category->name }}">
			@endforeach
		</datalist>
	</td>
	<td><input type="text" name="published_date" id="published_date" placeholder="Published Date"></td>
	<td><input type="text" name="borrowed" placeholder="Borrowed?" disabled></td>
	<td><input type="text" name="actions" placeholder="Actions" disabled></td>
@endsection

@section('data_url', route('books.data'))

@section('filter_data')
	id: $('#id').val(),
	name: $('#name').val(),
	author: $('#author').val(),
	category: $('#category').val(),
	published_date: $('#published_date').val(),
@endsection

resources/views/books/show.blade.php
@extends('layouts.pagination_script')

@section('title', 'Book View')

@section('header_content')
	<h1>
        Book View <a href="{{ route('books.edit', $book->id) }}" class="pull_right"><span class="glyphicon glyphicon-edit" aria-hidden="true" title="Edit Book"></a>
    </h1>
	<div class="col-md-12">
		<table>
			<tr>
				<td>ID</td><td>{{ $book->id }}</td>
			</tr>
			<tr>
				<td>Name</td><td>{{ $book->name }}</td>
			</tr>
			<tr>
				<td>Author</td><td>{{ $book->author }}</td>
			</tr>
			<tr>
				<td>Category</td><td><a href="{{ route('categories.show', $book->category->id) }}">{{ $book->category->name }}</td>
			</tr>
			<tr>
				<td>Published Date</td><td>{{ $book->published_date }}</td>
			</tr>
			@if($book->borrowed)
				<tr>
					<td>Borrowed By</td><td><a href="{{ route('users.show', $book->user->id) }}">{{ $book->user->name }}</a></td>
				</tr>
			@endif
		</table>
		@if(!$book->borrowed)
			<div class="text-center">
				<button class="lend_book btn btn-primary" data-toggle="modal" data-target="#lendBookModal" data-url="{{ route('books.borrow',$book->id) }}">Lend Book</button>
			</div>
		@endif
	</div>
	<div class="modal fade" id="lendBookModal" tabindex="-1" role="dialog" aria-labelledby="lendBookLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="lendBookLabel">Return Book</h4>
				</div>
				<div class="modal-body">
					<p>Select a user to lend the book</p>
@endsection

@section('table_head')
	<td><input type="number" name="id" id="id" placeholder="ID"></td>
	<td><input type="text" name="name" id="name" placeholder="Name"></td>
	<td><input type="email" name="email" id="email" placeholder="e-mail"></td>
	<td><input type="text" name="book_count" id="book_count" placeholder="Borrowed Books" disabled></td>
	<td><input type="text" name="actions" placeholder="Actions" disabled></td>
@endsection

@section('other_content')
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('data_url', route('users.data'))

@section('filter_data')
	id: $('#id').val(),
	name: $('#name').val(),
	email: $('#email').val(),
	book_id: "{{ $book->id }}",
@endsection

@section('custom_scripts')
	$('#lendBookModal').on('show.bs.modal', function (event) {
		var button = $(event.relatedTarget);
		var modal = $(this);
	})

	$('body').on('click', 'a.lend_book', function(e) {
        e.preventDefault();
        var route = $(this).attr('href');
        var user_id = $(this).data('id');
        $.ajax({
            type: "POST",
            url : route,
            data: {
                _token: "{{ csrf_token() }}",
            	user_id: user_id,
            },
        }).done(function (result) {
            window.location.href = "{{ route('books.show', $book->id) }}";
        }).fail(function () {
            alert('The data could not be loaded.');
        });
        $('#lendBookModal').modal('hide');
    });
@endsection