routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('books.index');
});

Route::post('books/{book}/borrow', 'BookController@borrow')->name('books.borrow');
Route::post('books/{book}/retrieve', 'BookController@retrieve')->name('books.retrieve');
Route::post('books/data', 'BookController@data')->name('books.data');
Route::resource('books', 'BookController');

Route::post('categories/data', 'CategoryController@data')->name('categories.data');
Route::resource('categories', 'CategoryController');

Route::post('users/data', 'UserController@data')->name('users.data');
Route::resource('users', 'UserController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
	use SoftDeletes;
	
    protected $fillable = ['name', 'description'];

    protected $dates =['created_at', 'updated_at', 'deleted_at'];

    function books(){
    	return $this->hasMany('App\Book');
    }

    function getBookCountAttribute(){
    	return $this->books()->count();
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class CategoryController extends Controller
{
    private $validatorRules = [
        'name' => 'required|min:3|max:255',
        'description' => 'required|min:3|max:255'
    ];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, $this->validatorRules);
        $category = Category::create([
            'name' => $request->name,
            'description' => $request->description
            ]);
        if($category){
            return redirect()->route('categories.show', ['category'=>$category->id]);
        }else{
            return redirect()->route('categories.create', ['errors' => ['unespecified_error' => 'there was a problem storing the category']]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::find($id)->load('books');
        if($category)
            return view('categories.show', ['category' => $category]);
        else
            return redirect()->route('categories.index', ['error' => 'The specified category could not be found']);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        if($category)
            return view('categories.edit', ['category' => $category]);
        else
            return redirect()->route('categories.index', ['error' => 'The specified category could not be found']);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, $this->validatorRules);
        $category = Category::find($id);
        if($category){
            $category->name = $request->name;
            $category->description = $request->description;
            $category->save();
            return redirect()->route('categories.show', ['category'=>$category->id]);
        }
        else
            return redirect()->route('categories.index', ['error' => 'The specified category could not be found']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        if($category){
            if($category->delete())
                $json=['success' => true, 'msg' => 'the category was deleted'];
            else
                $json=['success' => flase, 'msg' => 'the category cold not be deleted'];
            return response()->json($json)->header('Content-Type', 'application/json');
        }
        else
            return response()->json(['success' => false, 'msg' => 'the specified category could not be found'])->header('Content-Type', 'application/json');
    }

    public function data(Request $request){
        $id = $request->has('id') ? $request->id : null;
        $name = $request->has('name') ? $request->name : null;
        $description = $request->has('description') ? $request->description : null;

        $categories_query = Category::query();
        if($id)
            $categories_query->whereId($id);
        if($name)
            $categories_query->whereName($name);
        if($description)
            $categories_query->whereDescription($description);

        $limit = 10;
        $totalTabs = ceil($categories_query->count()/$limit);

        $index = $request->has('index') ? ($request->index > $totalTabs ? $totalTabs : $request->index) : 1;
        $offset = ($index-1)*$limit;

        $categories = $categories_query->take($limit)->skip($offset)->get();

        $formatted = '';
        foreach ($categories as $category) {
            $formatted .= '<tr>';
            $formatted .= ' <td>'.$category->id.'</td>';
            $formatted .= ' <td>'.$category->name.'</td>';
            $formatted .= ' <td>'.$category->description.'</td>';
            $formatted .= ' <td>'.$category->book_count.'</td>';
            $formatted .= ' <td>';
            $formatted .= '     <a href="'.route('categories.show',$category->id).'"><span class="glyphicon glyphicon-info-sign" aria-hidden="true" title="Info"></span></a>';
            $formatted .= '     <a href="'.route('categories.edit',$category->id).'"><span class="glyphicon glyphicon-edit" aria-hidden="true" title="Edit"></span></a>';
            $formatted .= '     <a href="'.route('categories.destroy',$category->id).'" class="destroy_button"><span class="glyphicon glyphicon-remove red" aria-hidden="true" title="Remove"></span></a>';
            $formatted .= ' </td>';
            $formatted .= '</tr>';
        }

        $controls = PaginationHelper::getPaginationControls($index, $totalTabs);

        return response()->json(['success' => true, 'data' => $formatted, 'controls' => $controls])->header('Content-Type', 'application/json');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.default')

@section('title', 'Category Creation')

@section('content')
	<h1>
        Category Create
    </h1>
    
    @if (count($errors) > 0)
	    <div class="alert alert-danger">
	    	<ul>
			    @foreach($errors->all() as $error)
			    	<li>{{ $error }}</li>
			    @endforeach
	    	</ul>
	    </div>
    @endif

	<div class="col-md-12 text-center">
		<form id="new_category" action="{{ route('categories.store') }}" method="post">
			{{ csrf_field() }}
			<div class="form-group">
				<label for="name">Name:</label>
				<input type="text" name="name" id="name" placeholder="Name" pattern=".{3,}" required title="3 characters minimum">
			</div>
			<div class="form-group">
				<label for="description">Description:</label>
				<textarea name="description" id="description" placeholder="Description" pattern=".{3,}" required title="3 characters minimum"></textarea>
			</div>
			<div class="form-group">
				<input type="submit" name="create_category" id="create_category" class="btn btn-primary">
			</div>
		</form>
	</div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.default')

@section('title', 'Category Edit')

@section('content')
	<h1>
        Category Edit
    </h1>
    
    @if (count($errors) > 0)
	    <div class="alert alert-danger">
	    	<ul>
			    @foreach($errors->all() as $error)
			    	<li>{{ $error }}</li>
			    @endforeach
	    	</ul>
	    </div>
    @endif

	<div class="col-md-12 text-center">
		<form id="new_category" action="{{ route('categories.update', $category->id) }}" method="post">
			{{ csrf_field() }}
			<input type="hidden" name="_method" value="PATCH">
			<div class="form-group">
				<label for="name">Name:</label>
				<input type="text" name="name" id="name" placeholder="Name" pattern=".{3,}" required title="3 characters minimum" value="{{ $category->name }}">
			</div>
			<div class="form-group">
				<label for="description">Description:</label>
				<textarea name="description" id="description" placeholder="Description" pattern=".{3,}" required title="3 characters minimum">{{ $category->description }}</textarea>
			</div>
			<div class="form-group">
				<input type="submit" name="update_category" id="update_category" class="btn btn-primary">
			</div>
		</form>
	</div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.general_index')

@section('title', 'Categories')
@section('create_route', route('categories.create'))

@section('table_head')
	<td><input type="number" name="id" id="id" placeholder="ID"></td>
	<td><input type="text" name="name" id="name" placeholder="Name"></td>
	<td><input type="text" name="description" id="description" placeholder="Description"></td>
	<td><input type="text" name="book_count" id="book_count" placeholder="Books" disabled></td>
	<td><input type="text" name="actions" placeholder="Actions" disabled></td>
@endsection

@section('data_url', route('categories.data'))

@section('filter_data')
	id: $('#id').val(),
	name: $('#name').val(),
	description: $('#description').val(),
@endsection

resources/views/categories/show.blade.php
@extends('layouts.pagination_script')

@section('title', 'Category View')

@section('header_content')
	<h1>
        Category View <a href="{{ route('categories.edit', $category->id) }}" class="pull_right"><span class="glyphicon glyphicon-edit" aria-hidden="true" title="Edit Category"></a>
    </h1>
	<div class="col-md-12">
		<table>
			<tr>
				<td>ID</td><td>{{ $category->id }}</td>
			</tr>
			<tr>
				<td>Name</td><td>{{ $category->name }}</td>
			</tr>
			<tr>
				<td>Description</td><td>{{ $category->description }}</td>
			</tr>
		</table>
	</div>
	<h2>Books with this Category</h2>
@endsection

@section('table_head')
	<td><input type="number" name="id" id="id" placeholder="ID"></td>
	<td><input type="text" name="name" id="name" placeholder="Name"></td>
	<td><input type="text" name="author" id="author" placeholder="Author"></td>
	<td><input type="text" name="published_date" id="published_date" placeholder="Published Date"></td>
	<td><input type="text" name="borrowed" placeholder="Borrowed?" disabled></td>
	<td><input type="text" name="actions" placeholder="Actions" disabled></td>
@endsection

@section('data_url', route('books.data'))

@section('filter_data')
	category_id: {{$category->id}},
	id: $('#id').val(),
	name: $('#name').val(),
	author: $('#author').val(),
	published_date: $('#published_date').val(),
@endsection