routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('books.index');
});

Route::post('books/{book}/borrow', 'BookController@borrow')->name('books.borrow');
Route::post('books/{book}/retrieve', 'BookController@retrieve')->name('books.retrieve');
Route::post('books/data', 'BookController@data')->name('books.data');
Route::resource('books', 'BookController');

Route::post('categories/data', 'CategoryController@data')->name('categories.data');
Route::resource('categories', 'CategoryController');

Route::post('users/data', 'UserController@data')->name('users.data');
Route::resource('users', 'UserController');

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Library - @yield('title')</title>
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{{ asset('css/library.css') }}">
    </head>
    <body>
        <header class="title m-b-md">
            Library App
        </header>
        <div id="navigation text-center">
            <ul class="nav nav-tabs nav-justified">
                <li role="presentation"{!! (Request::is('books') || Request::is('books/*') ? ' class="active"' : '') !!}><a href="{{ route('books.index') }}">Books</a></li>
                <li role="presentation"{!! (Request::is('categories') || Request::is('categories/*') ? ' class="active"' : '') !!}><a href="{{ route('categories.index') }}">Categories</a></li>
                <li role="presentation"{!! (Request::is('users') || Request::is('users/*') ? ' class="active"' : '') !!}><a href="{{ route('users.index') }}">Users</a></li>
            </ul>
        </div>

        <div class="container">
            @yield('content')
        </div>
        @yield('footer_scripts')
    </body>
</html>

resources/views/layouts/general_index.blade.php
@extends('layouts.pagination_script')

@section('header_content')
    <h1>
        @yield('title') 
        <a href="@yield('create_route')" class="create_new_entry pull_right"><span class="glyphicon glyphicon-plus" aria-hidden="true" title="Create new entry"></a>
        <a href="#" class="refresh_and_filter pull_right"><span class="glyphicon glyphicon-refresh" aria-hidden="true" title="Refresh and Filter"></a>
        <a href="#" class="clear_filters pull_right"><span class="glyphicon glyphicon-remove" aria-hidden="true" title="Clear Filter Fields"></a>
    </h1>
@endsection

@section('custom_scripts')
    $('body').on('click', 'a.destroy_button', function(e) {
        e.preventDefault();
        var selection = confirm("Are you shure you want to destroy the element?");
        var route = $(this).attr('href');
        if(selection == true){
            $.ajax({
                type: "POST",
                url : route,
                data: {_method: "DELETE", _token: "{{ csrf_token() }}"},
            }).done(function (result) {
                getData($('.pagination a.active').data('val'))
            }).fail(function () {
                alert('The elemetn could not be deleted.');
            });
        }
    });
@endsection

resources/views/layouts/pagination_script.blade.php
@extends('layouts.default')

@section('content')
    @yield('header_content')
    <div id="data-table" class="col.md-6 text-center">
        <table>
            <thead>
                @yield('table_head')
            </thead>
            <tbody>
                
            </tbody>
        </table>
        <div class="pagination text-center">
            
        </div>
    </div>
    @yield('other_content')
@endsection

@section('footer_scripts')
<script>
    $( document ).ready(function() {
        $.ajaxSetup({
            headers: { 'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content') }
        });

        getData(1);

        $('body').on('click', 'a.refresh_and_filter', function(e) {
            e.preventDefault();
            var route = $(this).attr('href');
            getData(1)
        });

        $('body').on('click', 'a.clear_filters', function(e) {
            e.preventDefault();
            $('input').val("");
            getData(1);
        });

        $('body').on('click', '.pagination a', function(e) {
            e.preventDefault();
            if(!$(this).hasClass('dissabled'))
                getData($(this).data('val'));
        });

        function getData(index) {
            $.ajax({
                type: "POST",
                url : "@yield('data_url')",
                data: {
                    index: index,
                    _token: "{{ csrf_token() }}",
                    @yield('filter_data')
                },
            }).done(function (result) {
                $('#data-table tbody').html(result.data);
                $('.pagination').html(result.controls);
            }).fail(function () {
                alert('The data could not be loaded.');
            });
        }

        @yield('custom_scripts')
    });
</script>
@endsection